import { getAllTracksQuery, getPlaylistTracksQuery, getPlaylistByIdQuery } from '~/shared/queries'
import { type Track } from '~/dexie.storage'

export const usePlayer = defineStore('player', () => {
  const currentPlaylistId = ref<string | null>(null)
  const currentTrackId = ref<string | null>(null)
  const shuffle = ref(false)
  const shuffleQueue = ref<Track[]>([])
  const isFullscreenOpen = ref(false)

  const tracks = useDexieLiveQueryWithDeps(currentPlaylistId, (id?: string) => {
    if (id) {
      return getPlaylistTracksQuery(id)
    }
    return getAllTracksQuery()
  })

  const currentPlaylist = useDexieLiveQueryWithDeps(currentPlaylistId, (id?: string) => {
    if (id) {
      return getPlaylistByIdQuery(id)
    }
    return undefined
  })

  function generateShuffleQueue() {
    if (!tracks.value || tracks.value.length === 0) {
      shuffleQueue.value = []
      return
    }
    const shuffled = [...tracks.value].sort(() => Math.random() - 0.5)
    // Avoid starting with the same track as current if possible
    if (shuffled.length > 1 && shuffled[0]?.id === currentTrackId.value) {
      const swapIndex = Math.floor(Math.random() * (shuffled.length - 1)) + 1
      const first = shuffled[0]!
      const swap = shuffled[swapIndex]!
      shuffled[0] = swap
      shuffled[swapIndex] = first
    }
    shuffleQueue.value = shuffled
  }

  watch([tracks, shuffle], () => {
    if (shuffle.value) {
      generateShuffleQueue()
    }
  }, { immediate: true })

  const shuffledTracks = computed(() => shuffle.value ? shuffleQueue.value : tracks.value)

  const currentTrack = computed(() =>
    tracks.value?.find((t) => t.id === currentTrackId.value),
  )

  const title = useTitle()
  watch(
    currentTrack,
    (val) => {
      title.value = val?.name ?? 'mscx'
    },
    {
      immediate: true,
    },
  )

  async function switchToNextTrack() {
    if (!shuffledTracks.value) return
    const index = shuffledTracks.value?.findIndex((t) => t.id === currentTrackId.value)
    if (index === -1) return
    const nextIndex = (index + 1) % shuffledTracks.value.length
    if (nextIndex === 0 && shuffle.value) {
      // End of shuffle queue, regenerate
      generateShuffleQueue()
      currentTrackId.value = shuffleQueue.value[0]?.id ?? null
    } else {
      currentTrackId.value = shuffledTracks.value[nextIndex]?.id ?? null
    }
  }

  async function switchToPreviousTrack() {
    if (!shuffledTracks.value) return
    const index = shuffledTracks.value?.findIndex((t) => t.id === currentTrackId.value)
    if (index === -1) return
    const prevIndex = index === 0 ? shuffledTracks.value.length - 1 : index - 1
    currentTrackId.value = shuffledTracks.value[prevIndex]?.id ?? null
  }

  async function startPlayList(id: string) {
    currentPlaylistId.value = id
    const changed = await until(tracks).changed({ timeout: 500 })
    if (changed?.length) {
      if (shuffle.value) {
        // Shuffle queue should be generated by watch
        currentTrackId.value = shuffleQueue.value[0]?.id ?? null
      } else {
        currentTrackId.value = changed[0]?.id ?? null
      }
    } else {
      currentPlaylistId.value = null
      currentTrackId.value = null
    }
  }

  async function stopPlaylist() {
    currentPlaylistId.value = null
    currentTrackId.value = null
  }

  function toggleShuffle() {
    shuffle.value = !shuffle.value
  }

  function openFullscreen() {
    isFullscreenOpen.value = true
  }

  function closeFullscreen() {
    isFullscreenOpen.value = false
  }

  return {
    currentPlaylistId: readonly(currentPlaylistId),
    currentPlaylist,
    currentTrackId,
    currentTrack,
    shuffle: readonly(shuffle),
    isFullscreenOpen: readonly(isFullscreenOpen),
    toggleShuffle,
    openFullscreen,
    closeFullscreen,
    startPlayList,
    stopPlaylist,
    switchToNextTrack,
    switchToPreviousTrack,
  }
})
